{{- if .Values.openmetadata.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: openmetadata-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app: openmetadata
    component: server
spec:
  type: {{ .Values.global.networking.type }}
  {{- if eq .Values.global.networking.type "NodePort" }}
  ports:
    - port: 8585
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.openmetadata.nodePort }}
    - port: 8586
      targetPort: http-admin
      protocol: TCP
      name: http-admin
  {{- else if eq .Values.global.networking.type "LoadBalancer" }}
  ports:
    - port: 8585
      targetPort: http
      protocol: TCP
      name: http
    - port: 8586
      targetPort: http-admin
      protocol: TCP
      name: http-admin
  {{- else }}
  ports:
    - port: 8585
      targetPort: http
      protocol: TCP
      name: http
    - port: 8586
      targetPort: http-admin
      protocol: TCP
      name: http-admin
  {{- end }}
  selector:
    app: openmetadata
    component: server
{{- end }}
