{{- if .Values.traefik.enabled }}
{{- if .Values.traefik.certResolver.cloudflare.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: {{ .Values.global.namespace }}
  labels:
    app: traefik
    layer: infrastructure
type: Opaque
stringData:
  CF_API_TOKEN: {{ .Values.traefik.certResolver.cloudflare.apiToken | quote }}
{{- end }}
{{- end }}
